import React, { useState } from 'react';
import { Link } from 'react-router-dom';
import { useSimulation } from '../context/SimulationContext';
import { StatusBadge } from '../components/StatusBadge';
import {
  Layers,
  Search,
  Filter,
  ExternalLink,
  ShieldAlert,
  CheckCircle,
  ArrowRight,
  Trash2
} from 'lucide-react';

export const IncidentsPage: React.FC = () => {
  const { incidents, deleteIncident } = useSimulation();
  const [searchTerm, setSearchTerm] = useState('');
  const [statusFilter, setStatusFilter] = useState<string>('all');

  const filteredIncidents = incidents.filter(inc => {
    const matchesSearch = inc.title.toLowerCase().includes(searchTerm.toLowerCase()) ||
      inc.id.toLowerCase().includes(searchTerm.toLowerCase()) ||
      inc.zone.toLowerCase().includes(searchTerm.toLowerCase());
    const matchesStatus = statusFilter === 'all' || inc.status === statusFilter;
    return matchesSearch && matchesStatus;
  });

  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-6 space-y-6">

      {/* Header */}
      <div className="flex flex-wrap items-center justify-between gap-4 pb-4 border-b border-sentinel-border">
        <div>
          <h1 className="text-xl sm:text-2xl font-mono font-bold text-slate-100 flex items-center gap-2">
            <Layers className="w-6 h-6 text-sentinel-accent" />
            <span>INCIDENT CASE DOSSIERS</span>
          </h1>
          <p className="text-xs font-sans text-slate-400 mt-0.5">
            Correlated Situational Reports Generated by the Sentinel Engine
          </p>
        </div>

        <Link to="/simulation" className="flex items-center gap-1.5 px-4 py-2 rounded-lg bg-sentinel-accent text-slate-950 font-mono font-bold text-xs uppercase tracking-wider">
          <span>Create Scenario</span>
        </Link>
      </div>

      {/* Search & Filter Controls */}
      <div className="flex flex-wrap items-center justify-between gap-3 p-4 rounded-xl bg-sentinel-card border border-sentinel-border">
        <div className="flex items-center gap-2 flex-1 max-w-md bg-sentinel-surface px-3 py-2 rounded-lg border border-sentinel-border">
          <Search className="w-4 h-4 text-slate-400" />
          <input
            type="text"
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            placeholder="Search by ID, title, zone, or location..."
            className="w-full bg-transparent text-xs text-slate-200 placeholder-slate-500 focus:outline-none font-mono"
          />
        </div>

        <div className="flex items-center gap-2 text-xs font-mono">
          <Filter className="w-4 h-4 text-slate-400" />
          <span className="text-slate-400">Filter:</span>
          {['all', 'critical', 'elevated', 'acknowledged', 'resolved'].map((s) => (
            <button
              key={s}
              onClick={() => setStatusFilter(s)}
              className={`px-3 py-1 rounded capitalize transition-colors cursor-pointer ${statusFilter === s
                ? 'bg-sentinel-accent text-slate-950 font-bold'
                : 'bg-sentinel-surface text-slate-400 hover:text-white'
                }`}
            >
              {s}
            </button>
          ))}
        </div>
      </div>

      {/* Incidents Grid */}
      {filteredIncidents.length === 0 ? (
        <div className="p-12 rounded-2xl bg-sentinel-card border border-sentinel-border text-center space-y-3">
          <ShieldAlert className="w-10 h-10 text-slate-600 mx-auto" />
          <h3 className="font-mono text-base font-bold text-slate-300">No Incidents Found</h3>
          <p className="text-xs text-slate-500 font-sans max-w-sm mx-auto">
            No incidents match your filter. Start a synthetic sensor scenario to generate incidents.
          </p>
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5">
          {filteredIncidents.map((inc) => (
            <div key={inc.id} className="p-5 rounded-2xl bg-sentinel-card border border-sentinel-border hover:border-sentinel-accent/60 transition-all duration-200 flex flex-col justify-between group shadow-lg">
              <div className="space-y-3">
                <div className="flex items-center justify-between pb-2 border-b border-sentinel-border/50">
                  <span className="font-mono text-xs font-bold text-sentinel-accent group-hover:underline">{inc.id}</span>
                  <StatusBadge status={inc.status} size="sm" />
                </div>
                <div>
                  <h3 className="font-mono text-sm font-bold text-slate-100 group-hover:text-sentinel-accent transition-colors line-clamp-1">{inc.title}</h3>
                  <p className="text-xs font-mono text-slate-400 mt-1">Zone: {inc.zone} &bull; {inc.location}</p>
                </div>
                <p className="text-xs text-slate-300 font-sans line-clamp-2 leading-relaxed">{inc.summary}</p>
                <div className="p-2.5 rounded-lg bg-sentinel-surface border border-sentinel-border/50 space-y-1 font-mono text-[11px]">
                  <div className="flex justify-between text-slate-400"><span>Evidence Confidence:</span><span className="text-sentinel-accent font-bold">{(inc.confidence * 100).toFixed(0)}%</span></div>
                  <div className="flex justify-between text-slate-400"><span>Converged Sources:</span><span className="text-emerald-400 font-bold">{inc.events.length} Channels</span></div>
                  <div className="flex justify-between text-slate-400"><span>Recorded Time:</span><span className="text-slate-300">{inc.createdAt}</span></div>
                </div>
              </div>
              <div className="mt-4 pt-3 border-t border-sentinel-border/60 flex items-center justify-between">
                <span className="text-[10px] font-mono text-slate-500 uppercase">Category: {inc.category.replace('_', ' ')}</span>
                <div className="flex items-center gap-3">
                  <button onClick={() => deleteIncident(inc.id)} className="p-1.5 rounded text-slate-500 hover:text-red-300 hover:bg-red-950/30 transition-colors" title="Delete incident and related records">
                    <Trash2 className="w-3.5 h-3.5" />
                  </button>
                  <Link to={`/incidents/${inc.id}`} className="flex items-center gap-1 text-xs font-mono font-bold text-sentinel-accent hover:text-cyan-300">
                    <span>Open Dossier</span><ArrowRight className="w-3.5 h-3.5" />
                  </Link>
                </div>
              </div>
            </div>
          ))}
        </div>
      )}

    </div>
  );
};
